---
driver:
  name: vagrant
  customize:
    memory: 512

provisioner:
  name: chef_zero

platforms:
- name: debian-7.4
- name: ubuntu-14.04
- name: centos-6.5

suites:
- name: debian
  run_list: ["recipe[vagrant::default]"]
  excludes: ["centos-6.5"]
  attributes:
    vagrant:
      url: "https://dl.bintray.com/mitchellh/vagrant/vagrant_1.6.2_x86_64.deb"
      plugins: ["vagrant-omnibus"]

- name: rhel
  run_list: ["recipe[vagrant::default]"]
  excludes: ["ubuntu-14.04", "debian-7.4"]
  attributes:
    vagrant:
      url: "https://dl.bintray.com/mitchellh/vagrant/vagrant_1.6.2_x86_64.rpm"
      plugins: ["vagrant-omnibus"]